// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MembershipMessage.proto

package MembershipMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_JOIN   MsgType = 0
	MsgType_UPDATE MsgType = 1
	MsgType_LEAVE  MsgType = 2
	MsgType_PING   MsgType = 3
	MsgType_ACK    MsgType = 4
)

var MsgType_name = map[int32]string{
	0: "JOIN",
	1: "UPDATE",
	2: "LEAVE",
	3: "PING",
	4: "ACK",
}
var MsgType_value = map[string]int32{
	"JOIN":   0,
	"UPDATE": 1,
	"LEAVE":  2,
	"PING":   3,
	"ACK":    4,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MembershipMessage_53a8b470d4fb176d, []int{0}
}

type SrvStatus int32

const (
	SrvStatus_ACTIVE SrvStatus = 0
	SrvStatus_LEFT   SrvStatus = 1
	SrvStatus_FAIL   SrvStatus = 2
)

var SrvStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "LEFT",
	2: "FAIL",
}
var SrvStatus_value = map[string]int32{
	"ACTIVE": 0,
	"LEFT":   1,
	"FAIL":   2,
}

func (x SrvStatus) String() string {
	return proto.EnumName(SrvStatus_name, int32(x))
}
func (SrvStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MembershipMessage_53a8b470d4fb176d, []int{1}
}

type MembershipListItem struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string    `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Timestamp            uint64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status               SrvStatus `protobuf:"varint,5,opt,name=status,proto3,enum=MembershipMessage.SrvStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MembershipListItem) Reset()         { *m = MembershipListItem{} }
func (m *MembershipListItem) String() string { return proto.CompactTextString(m) }
func (*MembershipListItem) ProtoMessage()    {}
func (*MembershipListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_MembershipMessage_53a8b470d4fb176d, []int{0}
}
func (m *MembershipListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipListItem.Unmarshal(m, b)
}
func (m *MembershipListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipListItem.Marshal(b, m, deterministic)
}
func (dst *MembershipListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipListItem.Merge(dst, src)
}
func (m *MembershipListItem) XXX_Size() int {
	return xxx_messageInfo_MembershipListItem.Size(m)
}
func (m *MembershipListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipListItem.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipListItem proto.InternalMessageInfo

func (m *MembershipListItem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MembershipListItem) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MembershipListItem) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *MembershipListItem) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MembershipListItem) GetStatus() SrvStatus {
	if m != nil {
		return m.Status
	}
	return SrvStatus_ACTIVE
}

type MembershipMessage struct {
	Type                 MsgType               `protobuf:"varint,1,opt,name=type,proto3,enum=MembershipMessage.MsgType" json:"type,omitempty"`
	SrcPort              uint32                `protobuf:"varint,2,opt,name=srcPort,proto3" json:"srcPort,omitempty"`
	SrcIp                string                `protobuf:"bytes,3,opt,name=srcIp,proto3" json:"srcIp,omitempty"`
	List                 []*MembershipListItem `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MembershipMessage) Reset()         { *m = MembershipMessage{} }
func (m *MembershipMessage) String() string { return proto.CompactTextString(m) }
func (*MembershipMessage) ProtoMessage()    {}
func (*MembershipMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_MembershipMessage_53a8b470d4fb176d, []int{1}
}
func (m *MembershipMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembershipMessage.Unmarshal(m, b)
}
func (m *MembershipMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembershipMessage.Marshal(b, m, deterministic)
}
func (dst *MembershipMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembershipMessage.Merge(dst, src)
}
func (m *MembershipMessage) XXX_Size() int {
	return xxx_messageInfo_MembershipMessage.Size(m)
}
func (m *MembershipMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MembershipMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MembershipMessage proto.InternalMessageInfo

func (m *MembershipMessage) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_JOIN
}

func (m *MembershipMessage) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *MembershipMessage) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *MembershipMessage) GetList() []*MembershipListItem {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*MembershipListItem)(nil), "MembershipMessage.MembershipListItem")
	proto.RegisterType((*MembershipMessage)(nil), "MembershipMessage.MembershipMessage")
	proto.RegisterEnum("MembershipMessage.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("MembershipMessage.SrvStatus", SrvStatus_name, SrvStatus_value)
}

func init() {
	proto.RegisterFile("MembershipMessage.proto", fileDescriptor_MembershipMessage_53a8b470d4fb176d)
}

var fileDescriptor_MembershipMessage_53a8b470d4fb176d = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0x23, 0x5b, 0x49, 0xd6, 0xb3, 0x6c, 0xd0, 0x0e, 0x0b, 0x2b, 0x4a, 0x0e, 0x26, 0x50,
	0x30, 0x29, 0xe4, 0x90, 0xf6, 0xd2, 0x43, 0x0f, 0x26, 0x75, 0x8a, 0x5b, 0x27, 0x0d, 0x8a, 0x9b,
	0x7b, 0xfe, 0x88, 0x54, 0x50, 0x13, 0x61, 0xa9, 0x85, 0xbc, 0x4b, 0x9f, 0xa1, 0xcf, 0x58, 0xac,
	0xa6, 0xcd, 0xc1, 0xb9, 0xcd, 0x37, 0xfa, 0xbe, 0xd1, 0x4f, 0x23, 0xf8, 0x3f, 0x91, 0xc5, 0x4a,
	0x96, 0xe6, 0x59, 0xe9, 0x89, 0x34, 0x66, 0xb9, 0x95, 0x03, 0x5d, 0xee, 0xec, 0x0e, 0xff, 0xd6,
	0x0e, 0x7a, 0xef, 0x04, 0xf0, 0xd8, 0xcd, 0x94, 0xb1, 0xa9, 0x95, 0x05, 0x76, 0xc0, 0x53, 0x1b,
	0x4e, 0x42, 0x12, 0x51, 0xe1, 0xa9, 0x8d, 0xd3, 0x9a, 0x7b, 0x21, 0x89, 0x02, 0xe1, 0x29, 0x8d,
	0x08, 0x54, 0xef, 0x4a, 0xcb, 0xfd, 0x90, 0x44, 0x7f, 0x84, 0xab, 0xb1, 0x0b, 0x81, 0x55, 0x85,
	0x34, 0x76, 0x59, 0x68, 0x4e, 0x5d, 0xf4, 0xd8, 0xc0, 0x2b, 0x68, 0x19, 0xbb, 0xb4, 0xaf, 0x86,
	0x37, 0x43, 0x12, 0x75, 0x86, 0xdd, 0x41, 0x9d, 0x72, 0x5e, 0xbe, 0xcd, 0x9d, 0x47, 0x1c, 0xbc,
	0xbd, 0x0f, 0x02, 0x75, 0x68, 0x1c, 0x00, 0xb5, 0x7b, 0x2d, 0x1d, 0x5f, 0x67, 0x78, 0x76, 0x62,
	0xd2, 0xc4, 0x6c, 0xf3, 0xbd, 0x96, 0xc2, 0xf9, 0x90, 0x43, 0xdb, 0x94, 0xeb, 0x59, 0x05, 0xec,
	0x39, 0xe0, 0x6f, 0x89, 0xff, 0xa0, 0x69, 0xca, 0x75, 0xaa, 0xdd, 0x43, 0x02, 0xf1, 0x25, 0xf0,
	0x1a, 0xe8, 0x8b, 0x32, 0x96, 0xd3, 0xd0, 0x8f, 0x7e, 0x0f, 0xcf, 0x4f, 0xcd, 0xaf, 0xad, 0x4c,
	0xb8, 0x48, 0xff, 0x06, 0xda, 0x87, 0xbb, 0xf1, 0x17, 0xd0, 0xfb, 0xc7, 0x74, 0xca, 0x1a, 0x08,
	0xd0, 0x7a, 0x9a, 0xdd, 0xc6, 0x79, 0xc2, 0x08, 0x06, 0xd0, 0xcc, 0x92, 0x78, 0x91, 0x30, 0xaf,
	0x32, 0xcc, 0xd2, 0xe9, 0x1d, 0xf3, 0xb1, 0x0d, 0x7e, 0x3c, 0x7a, 0x60, 0xb4, 0x7f, 0x01, 0xc1,
	0xcf, 0x12, 0xaa, 0x58, 0x3c, 0xca, 0xd3, 0x45, 0xc2, 0x1a, 0x95, 0x37, 0x4b, 0xc6, 0x39, 0x23,
	0x55, 0x35, 0x8e, 0xd3, 0x8c, 0x79, 0xab, 0x96, 0xfb, 0xd5, 0xcb, 0xcf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x70, 0x05, 0xf3, 0xf0, 0x01, 0x00, 0x00,
}
